INSERT INTO agentic_synthesis_tasks (
    prompt_text,
    action_tags_json,
    llm_api_key,
    llm_base_url,
    llm_model_name,
    dataset_paths_json,
    output_file_path,
    status,
    total_files,
    processed_files,
    success_files,
    failed_files,
    started_time,
    finished_time,
    error_message
)
VALUES
(
    '为业务分析生成客户画像摘要与风险标签',
    '["summary", "classification", "risk"]',
    'demo-key-001',
    'https://api.openai.com/v1',
    'gpt-4.1-mini',
    '["datasets/customers_2025.csv", "datasets/transactions_q4.parquet"]',
    'outputs/task_001_customer_profile.json',
    'completed',
    24,
    24,
    24,
    0,
    '2026-03-07 10:00:00',
    '2026-03-07 10:12:34',
    NULL
),
(
    '对销售日报做异常检测并输出告警建议',
    '["anomaly-detection", "alerting"]',
    'demo-key-002',
    'https://api.openai.com/v1',
    'gpt-4.1',
    '["datasets/sales_daily_2026_03.csv"]',
    'outputs/task_002_sales_anomaly.json',
    'running',
    120,
    86,
    82,
    4,
    '2026-03-07 13:50:00',
    NULL,
    NULL
),
(
    '从实验日志中提取关键失败原因并归类',
    '["extraction", "root-cause-analysis"]',
    'demo-key-003',
    'https://api.openai.com/v1',
    'gpt-4o-mini',
    '["datasets/exp_logs_202602.jsonl", "datasets/exp_logs_202603.jsonl"]',
    'outputs/task_003_exp_failure_rca.json',
    'failed',
    40,
    17,
    11,
    6,
    '2026-03-07 11:20:00',
    '2026-03-07 11:27:42',
    '部分日志文件编码异常，解析中断'
),
(
    '整理多源数据并生成统一字段映射说明',
    '["schema-mapping", "documentation"]',
    'demo-key-004',
    'https://api.openai.com/v1',
    'gpt-4.1-mini',
    '["datasets/source_a.xlsx", "datasets/source_b.csv", "datasets/source_c.json"]',
    'outputs/task_004_schema_mapping.md',
    'pending',
    0,
    0,
    0,
    0,
    NULL,
    NULL,
    NULL
);